### ISSUE TITLE
Installation failure 

### ISSUE THREAD

**Issue by laudiblellc** [markubiak/minidsp-control#1]
Hi,
I am not experienced in npm or nodejs and get a failure when installing on an RPi 4. I've attached a log that appears after I git clone your repository, then enter the directory and perform npm install. This is on a fresh Raspbian installation. 
[2020-09-15T20_00_18_840Z-debug.log](https://github.com/markubiak/minidsp-control/files/5228042/2020-09-15T20_00_18_840Z-debug.log)

**Comment by laudiblellc** [comment]
I googled it and apt-installing lubudev-dev solved the issue. Maybe you want to add that as an install prereq. Thanks!

**Comment by laudiblellc** [comment]
Now, the monitor fails this way:
nodejs ./minidsp.js monitor
/home/pi/node-minidsp/node_modules/node-hid/nodehid.js:49
    this._raw = new (Function.prototype.bind.apply(binding.HID,
                ^

Error: cannot open device with vendor id 0x2752 and product id 0x11
    at new HID (/home/pi/node-minidsp/node_modules/node-hid/nodehid.js:49:17)
    at new USBTransport (/home/pi/node-minidsp/src/transport/usb.js:15:27)
    at device (/home/pi/node-minidsp/minidsp.js:57:43)
    at Command.program.command.description.action (/home/pi/node-minidsp/minidsp.js:119:13)
    at Command.listener (/home/pi/node-minidsp/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:198:13)
    at Command.parseArgs (/home/pi/node-minidsp/node_modules/commander/index.js:651:12)
    at Command.parse (/home/pi/node-minidsp/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/home/pi/node-minidsp/minidsp.js:152:9)
    at Module._compile (internal/modules/cjs/loader.js:778:30)

**Comment by laudiblellc** [comment]
OK, executing the script with sudo works, but none of the commands exit automatically, but need to be killed. Any ideas?  Thanks,
